[now]
title = "NAVER NOW. ─ 지금 방송중"
url = "http://now.naver.com/listen"
entrySelector = "div.layer_main div.layer_content div.onair_list div.swiper-container div.swiper-wrapper div.swiper-slide"
titleSelector = "p.description"
linkSelector = "a.link"
contentSelector = "span.title"
imageSelector = "div.thumb_area img.thumbnail"
waitUntil = "networkidle"

[navertv]
title = "네이버 나우. ─ NAVER TV"
url = "https://tv.naver.com/nowkr/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"