[now]
title = "NAVER NOW. ─ 지금 방송중"
url = "http://now.naver.com/listen"
entrySelector = "div.layer_main div.layer_content div.onair_list div.swiper-container div.swiper-wrapper div.swiper-slide"
titleSelector = "p.description"
linkSelector = "a.link"
contentSelector = "span.title"
imageSelector = "a.link div.thumb_area img.thumbnail"
waitUntil = "networkidle"
onFail = "stale"

[navertv]
title = "네이버 나우. ─ NAVER TV"
url = "https://tv.naver.com/nowkr/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[naverpost]
title = "NAVER NOW. ─ 네이버 포스트"
url = "https://m.post.naver.com/my.nhn?memberNo=46872110"
entrySelector = "ul.lst_feed li._cds.check_visible"
titleSelector = "strong.tit_feed.ell"
linkSelector = "div.text_area a.link_end"
imageSelector = "div.image_area a img"
contentSelector = "p.text_feed.ell"
waitUntil = "networkidle"

[linkinbio]
title = "NAVER NOW. ─ Link in Bio"
url = "https://linkin.bio/now-kr"
entrySelector = "section[class='tLb--content__postList eLb--content__postList qa--linkinbio_grid'] div[class='o--cardContainer tLb--content__cardContainer']"
titleSelector = "*"
linkSelector = "a.o--card"
imageSelector = "figure.o--card__mediaContainer img"
waitUntil = "networkidle"